language: java
addons:
  sonarcloud:
    organization: "nifori-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_LOGIN # encrypted value of your token
script:
  - mvn package
  - sonar-scanner -Dsonar.java.binaries=backend